# Generated by Django 4.2.7 on 2023-11-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_handle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram'),
        ),
    ]
