# Generated by Django 4.2.7 on 2023-11-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribed_to_bot',
            field=models.BooleanField(default=False, verbose_name='подписан на бота?'),
        ),
    ]
