# Generated by Django 4.2.7 on 2023-11-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.PositiveSmallIntegerField(verbose_name='продолжительность'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='периодичность'),
        ),
    ]
