# Generated by Django 4.2.7 on 2023-11-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_habit_periodic_task_habit_subscribed_to_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='id чата в Телеграме'),
        ),
    ]
