# Generated by Django 4.2.7 on 2023-11-06 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_habit_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='chat_id',
        ),
    ]
