# Generated by Django 4.2.7 on 2023-11-07 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_remove_habit_subscribed_to_bot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['-id'], 'verbose_name': 'привычка', 'verbose_name_plural': 'привычки'},
        ),
    ]
